identifier: search-indexer  
title: Search Indexer
blueprint: service
properties:
  language: java
  tier: tier2
  compliance_level: pilot
relations:
  owner: team-fulfillment
metadata:
  last_updated_by: matt
